= WalletLedgerExport
Sean Gilligan <https://github.com/msgilligan>
v0.0.2
:description: WalletLedgerExport README
:ledgerexport-version: 0.0.2

image:https://github.com/ConsensusJ/WalletLedgerExport/actions/workflows/gradle.yml/badge.svg?branch=master["GitHub Actions Gradle Build", link="https://github.com/ConsensusJ/WalletLedgerExport/actions/workflows/gradle.yml"] image:https://github.com/ConsensusJ/WalletLedgerExport/actions/workflows/graalvm.yml/badge.svg?branch=master["GitHub Actions Gradle Build", link="https://github.com/ConsensusJ/WalletLedgerExport/actions/workflows/graalvm.yml"]


Command-line tool for exporting Bitcoin Core (and Omni Core) transactions to Ledger CLI format.

== Features

* TBD

== Building

=== JDK Build

Prerequisite:: JDK 21 or later must be installed.

. Build and test
.. `./gradlew build`
. Build the tool and wrapper scripts.
.. `./gradlew ledger-export-tool:installDist`

To run the tool (via a generated shell script):

. `./ledger-export-tool/build/install/LedgerExport/bin/LedgerExport --help`

=== GraalVM Build

Prerequisite:: GraalVM 21 or later must be installed.

. Build and test
.. `./gradlew build`
. Build the native command-line tool.
.. `./gradlew nativeCompile`

To run the natively-compiled binary tool:

. `./ledger-export-tool/build/native/nativeCompile/LedgerExport --help`


== Running

You'll need a locally-running (i.e. accessible on localhost) Bitcoin Core (or Omni Core) with JSON-RPC service.  `LedgerExport` will find the username and password in the `bitcoin.conf` file and connect to your running `bitcoind` (or `omnicored`) instance. Use the `--help` command to view the available command-line options.


