name: GraalVM Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: [ '21' ]
        distribution: [ 'graalvm-community' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}-${{ matrix.distribution }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Verify Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: ./gradlew build asciidoctor nativeCompile --scan --info --stacktrace
      - name: Upload LedgerExport tool as artifact
        uses: actions/upload-artifact@v4
        with:
          name: LedgerExport-${{ matrix.os }}
          path: ledger-export-tool/build/native/nativeCompile/LedgerExport
